"""
Weekly Business Audit - Generates the Monday Morning CEO Briefing.

Responsibilities:
1. Analyze business performance vs goals
2. Audit accounting transactions (from Odoo or local CSVs)
3. Identify bottlenecks and proactive suggestions
4. Generate CEO Briefing markdown file
"""

import os
import sys
import json
import logging
from pathlib import Path
from datetime import datetime, timedelta

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

class WeeklyAudit:
    """Performs weekly business and accounting audits."""

    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.goals_file = self.vault_path / 'Business_Goals.md'
        self.briefings_folder = self.vault_path / 'Briefings'
        self.logs_folder = self.vault_path / 'Logs'
        self.done_folder = self.vault_path / 'Done'
        
        self.briefings_folder.mkdir(parents=True, exist_ok=True)
        self.logger = logging.getLogger('WeeklyAudit')

    def run_audit(self):
        """Run the full audit and generate briefing."""
        self.logger.info("Starting weekly audit...")
        
        # 1. Gather data
        goals = self._read_goals()
        activity = self._gather_weekly_activity()
        accounting = self._gather_accounting_data()
        
        # 2. Analyze
        summary = self._analyze_performance(goals, activity, accounting)
        
        # 3. Generate Briefing
        briefing_path = self._generate_briefing(summary)
        
        self.logger.info(f"Audit complete. Briefing generated: {briefing_path}")
        return briefing_path

    def _read_goals(self):
        """Read business goals from Obsidian."""
        if not self.goals_file.exists():
            return "No goals defined."
        return self.goals_file.read_text()

    def _gather_weekly_activity(self):
        """Gather completed tasks and logs from the last 7 days."""
        activity = []
        cutoff = datetime.now() - timedelta(days=7)
        
        # Check Done folder
        for f in self.done_folder.glob('*.md'):
            if datetime.fromtimestamp(f.stat().st_mtime) > cutoff:
                activity.append(f"Completed Task: {f.name}")
        
        # Check logs
        for f in self.logs_folder.glob('*.json'):
            if f.name.endswith('.json') and '-' in f.name:
                try:
                    date_str = f.stem
                    file_date = datetime.strptime(date_str, '%Y-%m-%d')
                    if file_date > cutoff:
                        logs = json.loads(f.read_text())
                        for entry in logs:
                            activity.append(f"Action: {entry.get('action_type', 'unknown')} - {entry.get('status', 'unknown')}")
                except:
                    pass
                    
        return activity

    def _gather_accounting_data(self):
        """Gather accounting data (placeholder for Odoo integration)."""
        # In a real setup, this would call OdooMCP
        return {
            "revenue": 2500.0,
            "expenses": 450.0,
            "pending_invoices": 3
        }

    def _analyze_performance(self, goals, activity, accounting):
        """Analyze performance and generate summary notes."""
        return {
            "period": f"{(datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')} to {datetime.now().strftime('%Y-%m-%d')}",
            "revenue": accounting["revenue"],
            "completed_count": len([a for a in activity if "Completed" in a]),
            "activity_summary": activity[:5], # Top 5
            "suggestions": [
                "I noticed social media engagement is up 15%. Consider increasing post frequency.",
                "3 invoices are pending for more than 7 days. Shall I send reminders?"
            ]
        }

    def _generate_briefing(self, summary):
        """Create the briefing markdown file."""
        date_str = datetime.now().strftime('%Y-%m-%d')
        filename = f"{date_str}_Monday_CEO_Briefing.md"
        filepath = self.briefings_folder / filename
        
        content = f"""---
generated: {datetime.now().isoformat()}
type: briefing
period: {summary['period']}
---

# Monday Morning CEO Briefing

## Executive Summary
The business is performing well. Revenue for the period is **${summary['revenue']}**.

## Performance Metrics
- **Completed Tasks:** {summary['completed_count']}
- **Revenue:** ${summary['revenue']}
- **Pending Actions:** {len(summary['activity_summary'])}

## Recent Activity Highlights
"""
        for act in summary['activity_summary']:
            content += f"- {act}\n"
            
        content += """
## Proactive Suggestions
"""
        for sugg in summary['suggestions']:
            content += f"- {sugg}\n"

        content += f"""
---
*Generated by AI Employee Weekly Audit v1.0*
"""
        filepath.write_text(content)
        return filepath

def main():
    # Assume vault is at root for now or passed via env
    vault_path = os.getenv('VAULT_PATH', './AI_Employee_Vault')
    audit = WeeklyAudit(vault_path)
    audit.run_audit()

if __name__ == '__main__':
    main()
